# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5037bbc5728cca75d01d735f05f3bf48c4911d49590343de600af9fd1a05eb136f85121a78f1cadefb333ae17d676f57a31c1210f99aff90722329d7ed976e3f

test:
  secret_key_base: b3573d2fb67ee7accc7a8f160b34b8cc14a2dc855ac3c8d87816dc864d9ea47ee151db65b83d14efa401ecd44442185aec832a363ee91f586e717949de3bc5d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
